---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  labels:
    app: {{ template "__CHART__.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "__CHART__.fullname" . }}
spec:
  commonName: __COMMON_NAME__
  dnsNames:
    - __DNS_SAN__
  issuerRef:
    # The "kind" can be either:
    #
    # A "cluster issuer", which handles cert management across that cluster or
    # An "issuer" which handles cert management only in that namespace
    kind: ClusterIssuer
    name: __ISSUER_NAME__
  secretName: __SECRET_FOR_TLS__
